# Data
output_path: output/
checkpoints_path: checkpoints/faster_rcnn/

# Model
max_epochs: 200
batch_size: 16
learning_rate: 1e-3
n_classes: 5
pretrained: True

# Augmentation
p_flip: 0
p_brightness_contrast: .5
p_rigid_body: .5
shift_limit: 0.05
scale_limit: 0.05
rotate_limit: 5
num_holes: 2
max_h_size: 80
max_w_size: 80
fill_value: 128
p_cutout: .5